Reviews
web-search-for-the-nearest-hospitals/backend pull request #135
Opened 2024-01-26 16:57 UTC by PavlovMaximYurevich

Добавлены отзывы

2024-01-27 09:53 UTC, PrudyvusP requested changes
Макс, всё супер, чисто по мелочи + миграцию закинуть

2024-01-27 09:53 UTC, PrudyvusP commented on backend/api/serializers.py
> +        slug_field='username',
Есть ощущение, что здесь должна быть почта, у нас юзернейм нигде не задействован

2024-01-27 09:53 UTC, PrudyvusP commented on backend/organizations/models/reviews.py
> +        return self.text
Миграцию нужно добавить)

2024-01-27 09:53 UTC, PrudyvusP commented on backend/api/views/review.py
> +        return Response(serializer.data)
Неплохо-неплохо)

2024-01-27 09:53 UTC, PrudyvusP commented on backend/api/views/review.py
> +from rest_framework import viewsets
когда не до чего докопаться, ревьюеры практикума приходили в импорты и выносили мозг за них))))))))))))0

2024-01-27 09:53 UTC, PrudyvusP commented on backend/organizations/models/reviews.py
> +        verbose_name='Организация',
related_name явно нужно указать

2024-01-27 09:53 UTC, PrudyvusP commented on backend/organizations/models/reviews.py
> +        default_related_name = 'reviews'
Если честно, не видел, что бы указывали здесь дефолтное имя
по идее как только добавляется вторая сущность, то может носить другое имя)

2024-01-27 12:41 UTC, PavlovMaximYurevich commented on backend/organizations/models/reviews.py
> +        default_related_name = 'reviews'
сделал для удобства)
во вью вместо  return self.get_organization().reviews.all()
Придётся тогда городить (Review.objects.filter(organization=self.get_organization())

2024-01-27 19:53 UTC, PrudyvusP requested changes

2024-01-27 19:53 UTC, PrudyvusP commented on backend/organizations/models/reviews.py
> +        related_name='organization',
reviews

2024-01-28 14:19 UTC, PrudyvusP approved these changes

2024-01-28 14:20 UTC, merged